### ISSUE TITLE
Pip package (temporary?)

### ISSUE THREAD

**Issue by do-me** [willccbb/mlx_parallm#6]
Hey Will, 
what do you think about creating a pip package (until your PR might be merged)? 
I'm currently building two applications based on this repo. Installing via pip would make it easier to set up.

**Comment by willccbb** [comment]
Sure, will try and publish as a package soon. 

TBD what the timeline on a PR to mlx_lm will be, I want to get repetition penalties working first so that it has the same feature set as standard `generate`, but have been hitting memory issues so far.

**Comment by willccbb** [comment]
Thought about it a bit -- I'm working on adding this functionality to mlx-vlm, which is registered with pypi, and then will try and add to mlx_lm after. Not sure it makes all that much sense as a standalone package. You're welcome to copy the code directly for your applications.  

It's possible I'll look into supporting more "parallel API server" features in the future, at which point I'd register as a package, but in the current state it's probably best to think of the repo as a standalone util rather than a full "library". Going to close for now.
